### PR TITLE
Add MinIO file server manifest JSON file

### PR DESCRIPTION
**Pull request by pgadige**
1. Created a new subdirectory, **io_manifests**
2. Added the manifest JSON file for **MinIO File Server** package.

Signed-off-by: pgadige <pooja.gadige@rapyuta-robotics.com>

### CODE REVIEW

**Comment by pgadige** [comment]
Appreciate feedback. Thank you.
cc: @HackToHell @shivamMg

**Review by shivamMg — COMMENTED** [review]
lgtm. the conventions followed here should be followed for other manifest files as well:

* directory name should be `io_manifests`
* manifest name should be `*_manifest.json`
* use of tabs for indentation
   * @pgadige would be great if you can comment the online tool you use for pretty printing json

**Comment by pgadige** [comment]
Thank you for your valuable feedback.
     
>       * @pgadige would be great if you can comment the online tool you use for pretty printing json
[JSONLint](https://jsonlint.com/) is the tool used for pretty printing JSON.

I shall upload the manifest files of all packages created in all of the walkthroughs in a separate PR.

**Comment by pgadige** [comment]
Added a README file to describe the contents of **io_manifests** sub-directory.

**Review by shivamMg — APPROVED** [review]

**Review by HackToHell — APPROVED** [review]

**Pull request merged**
